- name: Job template for "{{job_template_name_osp_instances}}"
  tower_job_template:
    name: "{{job_template_name_osp_instances}}"
    description: "{{job_template_name_osp_instances}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{osp_instances_playbook}}" 
    credential: "{{ssh_cred_name}}"
    job_type: run
    state: present 
    
#- name: Job template for OSP Instances
#  command: |
#    tower-cli job_template create --name "{{job_template_name_osp_instances}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_instances_playbook}}" --credential "{{ssh_cred_name}}"

### TODO: Fix / Introduce "associate_ig" token to module tower_job_template
- name: Associate IG to "{{job_template_name_osp_instances}}" job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_osp_instances}}" --instance-group "{{instance_group_name}}"

- name: Create vault credential "{{ vault_name }}"
  tower_credential:
    name: "{{ vault_name }}"
    description: "{{ vault_name }} Ansible Vault"
    organization: "{{org_name}}"
    vault_password: "{{ vault_password }}"
    kind: vault 

#- name: Create vault credential
#  command: |
#    tower-cli credential create --name "{{ vault_name }}" --organization "{{org_name}}" --inputs '{"vault_password":"ansible"}'  --credential-type "Vault"

- name: Job template for "{{job_template_name_3tier_app}}" Application
  tower_job_template:
    name: "{{job_template_name_3tier_app}}"
    description: "{{job_template_name_3tier_app}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{app_deploy_playbook}}"
    credential: "{{ssh_cred_name}}"
    vault_credential: "{{ vault_name }}"
    job_type: run
    state: present

#- name: Job template for 3tier app deploy on QA Env
#  command: |
#    tower-cli job_template create --name "{{job_template_name_3tier_app}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{app_deploy_playbook}}" --credential "{{ssh_cred_name}}" --vault-credential "{{ vault_name }}"

### TODO: Fix / Introduce "associate_ig" token to module tower_job_template
- name: Associate IG to "{{job_template_name_3tier_app}}" job template  
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_3tier_app}}" --instance-group "{{instance_group_name}}"

- name: Job template "{{job_template_name_osp_instances_delete}}" to delete OSP Instances
  tower_job_template:
    name: "{{job_template_name_osp_instances_delete}}" 
    description: "{{job_template_name_osp_instances_delete}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{osp_instances_delete_playbook}}" 
    credential: "{{ssh_cred_name}}"
    job_type: run
    state: present

#- name: Job template "{{job_template_name_osp_instances_delete}}" to delete OSP Instances
#  command: |
#    tower-cli job_template create --name "{{job_template_name_osp_instances_delete}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_instances_delete_playbook}}" --credential "{{ssh_cred_name}}"

### TODO: Fix / Introduce "associate_ig" token to module tower_job_template
- name: Associate IG to "{{job_template_name_osp_instances_delete}}" job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_name_osp_instances_delete}}" --instance-group "{{instance_group_name}}"

- name: Job template "{{job_template_smoke_osp}}" for smoke test osp instances
  tower_job_template:
    name: "{{job_template_smoke_osp}}"
    description: "{{job_template_smoke_osp}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{osp_smoke_playbook}}"
    credential: "{{ssh_cred_name}}"
    job_type: run
    state: present

#- name: Job template for smoke test osp instances
#  command: |
#    tower-cli job_template create --name "{{job_template_smoke_osp}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_smoke_playbook}}" --credential "{{ssh_cred_name}}"

### TODO: Fix / Introduce "associate_ig" token to module tower_job_template
- name: Associate IG to "{{job_template_smoke_osp}}" job template 
  command: |
    tower-cli job_template associate_ig --job-template "{{job_template_smoke_osp}}" --instance-group "{{instance_group_name}}"

- name: Job template "{{job_template_aws_provision}}" for Provisioning AWS env
  tower_job_template:
    name: "{{job_template_aws_provision}}"
    description: "{{job_template_aws_provision}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{aws_provision_playbook}}"
    credential: "{{ssh_cred_name}}"
    extra_vars_path: /tmp/aws_jq_vars.yml
    job_type: run
    state: present

#- name: Job template for Provisioning AWS env
#  command: |
#    tower-cli job_template create --name "{{job_template_aws_provision}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{aws_provision_playbook}}" --credential "{{ssh_cred_name}}" --extra-vars @/tmp/aws_jq_vars.yml


- name: Job template "{{job_template_aws_ssh_keys}}" for injecting AWS SSH keys
  tower_job_template:
    name: "{{job_template_aws_ssh_keys}}"
    description: "{{job_template_aws_ssh_keys}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{static_inventory_name}}"
    playbook: "{{aws_ssh_playbook}}"
    credential: "{{opentlc_cred_name}}"
    extra_vars_path: /tmp/tower_info.yml
    job_type: run
    state: present

#- name: Job template for injecting AWS SSH keys
#  command: |
#    tower-cli job_template create --name "{{job_template_aws_ssh_keys}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_ssh_playbook}}" --credential "{{opentlc_cred_name}}" --extra-vars @/tmp/tower_info.yml

- name: Job template "{{job_template_aws_status_check}}" for checking AWS instances status
  tower_job_template:
    name: "{{job_template_aws_status_check}}"
    description: "{{job_template_aws_status_check}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{ec2_dynamic_inventory}}"
    playbook: "{{aws_status_playbook}}"
    credential: "{{opentlc_cred_name}}"
    job_type: run
    state: present

#- name: Job template for checking AWS instances status
#  command: |
#    tower-cli job_template create --name "{{job_template_aws_status_check}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_status_playbook}}" --credential "{{opentlc_cred_name}}"

- name: Job template "{{job_template_name_3tier_app_aws}}" for 3tier AWS deploy
  tower_job_template:
    name: "{{job_template_name_3tier_app_aws}}"
    description: "{{job_template_name_3tier_app_aws}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{ec2_dynamic_inventory}}"
    playbook: "{{app_deploy_playbook}}"
    vault_credential: "{{ vault_name }}"
    job_type: run
    state: present

#- name: Job template for 3tier AWS deploy
#  command: |
#    tower-cli job_template create --name "{{job_template_name_3tier_app_aws}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{app_deploy_playbook}}"  --vault-credential "{{ vault_name }}"

- name: Job template "{{job_template_smoke_aws}}" for smoke test aws instances
  tower_job_template:
    name: "{{job_template_smoke_aws}}" 
    description: "{{job_template_smoke_aws}} Job Template"
    project: "{{proj_name}}"
    inventory: "{{ec2_dynamic_inventory}}"
    playbook: "{{aws_smoke_app_playbook}}"
    vault_credential: "{{ vault_name }}"
    job_type: run
    state: present

#- name: Job template for smoke test aws instances
#  command: |
##    tower-cli job_template create --name "{{job_template_smoke_aws}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_smoke_app_playbook}}" --vault-credential "{{ vault_name }}"
