# Create Homework Assignment project 
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: "{{ ssh_cred_name }}"
    organization: "{{org_name}}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ user_cred_name }}"

- name: Create Organization "{{org_name}}"
  command: |
    tower-cli organization create --name="{{org_name}}"

- name: Create Project "{{ proj_name }}" under "{{org_name}}" Organization
  command: |
    tower-cli project create --name "{{ proj_name }}" --organization "{{org_name}}" --scm-type git --scm-url "{{ scm_url }}" --wait

- name: Create Inventory "{{static_inventory_name}}" under "{{org_name}}" Organization
  command: |
    tower-cli inventory create --name "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group "{{group_name}}" in static inventory "{{static_inventory_name}}"
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name "{{group_name}}"

- name: Add workstation host "{{host_name}}" in tower inventory "{{static_inventory_name}}" 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host "{{host_name}}" to group "{{group_name}}"
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{org_name}}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data: /root/.ssh/id_rsa
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

